### ISSUE TITLE
Testing: Local Contexts plugin

### ISSUE THREAD

**Issue by matthewjmckinley** [omeka/plugin-LocalContexts#2]
Retrieve Local Contexts content (notices & labels) from the Local Contexts Hub API. Assign LC content to display in site footer, or save as item metadata, in selected or in all available languages.

Local Contexts test integration account project page:
https://sandbox.localcontextshub.org/communities/view/2/

Local Contexts test integration account API key to use in testing:
T0NsNURnUVIudFJhRVZId1Y2RWJsUldTQllEcWI3VzJLblFmbEJuNjk

Please test:

- Inserting only API key in LC API settings, returning all projects from project page (above) as well as Open to Collaborate notice
- Inserting API key and specific project id(s), separated by comma, returning only content specific to given project(s) as well as Open to Collaborate notice
- Assigning/removing LC content via API settings results
- Submitting API settings with no API key still returns already assigned LC content to remove
- Assigning LC content to Site, under Plugins (top bar)->Local Contexts->Configure, including selecting single and all languages respectively, and that it displays correctly in public site footer in all themes
- Assigning LC content as Exhibit content block, including selecting single and all languages respectively, and that it displays correctly on page in all themes
- Saving LC content as metadata (under Local Contexts tab) or as batch metadata edit, including selecting metadata field and saving as single & all languages respectively, and that it displays properly (i.e. as HTML with accompanying graphic) on both admin and public side
- Ensure that if more than 3 LC projects are available in all admin side menus (assign, remove, site settings, page block, item edit, batch item edit), that they are hidden under their title in a collapsible div
- Any other test ideas or issues you uncover

Thanks!

**Comment by aviannamiller** [comment]
As with https://github.com/omeka-s-modules/LocalContexts/issues/2, the plugin is looking pretty good and functioning as expected. First, a few issues that were the same as (or at least similar to) those that came up for the S module:

- > Inserting only API key in LC API settings, returning all projects from project page (above) as well as Open to Collaborate notice
  - The same eleven projects resulted as for S, so not seeing all of the projects from the linked project page
- > Inserting API key and specific project id(s), separated by comma, returning only content specific to given project(s) as well as Open to Collaborate notice
  - As with the module:
    > Entering multiples of the same project ID causes multiples of that project to show up in the assign list, although selecting duplicates only assigns the project once. Is there a way to ensure only one of that project would show up in the assign list even if the same ID is entered multiple times (though maybe this is less important since only one can be assigned anyway)?
- The language tags on Foundation and Lively could use some breathing room here as well (no real space between notice name and tag).

---

Now, new to just the Classic plugin testing experience:
- > Assigning/removing LC content via API settings results
  - I received the following error each time I attempted to remove content, although upon returning back to the plugin, the content was indeed removed: 
```
Zend_Http_Header_Exception_InvalidArgumentException: Invalid header value in /var/www/html/amiller/Classic/application/libraries/Zend/Http/Header/HeaderValue.php:124
Stack trace:
#0 /var/www/html/amiller/Classic/application/libraries/Zend/Http/Client.php(1601): Zend_Http_Header_HeaderValue::assertValid('<br />\r\n<b>Noti...')
#1 /var/www/html/amiller/Classic/application/libraries/Zend/Http/Client.php(467): Zend_Http_Client->_validateHeaderValue('<br />\r\n<b>Noti...')
#2 /var/www/html/amiller/Classic/application/libraries/Zend/Http/Client.php(439): Zend_Http_Client->setHeaders('x-api-key', '<br />\r\n<b>Noti...')
#3 /var/www/html/amiller/Classic/plugins/LocalContexts/controllers/LocalContextsController.php(160): Zend_Http_Client->setHeaders(Array)
#4 /var/www/html/amiller/Classic/plugins/LocalContexts/controllers/LocalContextsController.php(82): LocalContexts_LocalContextsController->fetchAPIdata('<br />\r\n<b>Noti...')
#5 /var/www/html/amiller/Classic/application/libraries/Zend/Controller/Action.php(516): LocalContexts_LocalContextsController->assignAction()
#6 /var/www/html/amiller/Classic/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('assignAction')
#7 /var/www/html/amiller/Classic/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#8 /var/www/html/amiller/Classic/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(106): Zend_Controller_Front->dispatch()
#9 /var/www/html/amiller/Classic/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#10 /var/www/html/amiller/Classic/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#11 /var/www/html/amiller/Classic/admin/index.php(28): Omeka_Application->run()
#12 {main}
```
- > Assigning LC content to Site, under Plugins (top bar)->Local Contexts->Configure, including selecting single and all languages respectively, and that it displays correctly in public site footer in all themes
  - All themes, except for Santa Fe, have layout issues in the footer: 

    <img width="986" alt="LC content in footer. Text content is misaligned and overlapping graphics and other text" src="https://github.com/user-attachments/assets/b555987f-71ee-4e78-a3b5-1de1a1e3f7e2" />

  - Freedom has a text to background contrast issue: 

    <img width="989" alt="LC content in footer of site with Freedom theme. Text is light with low contrast on white background. A portion of text is highlighted to better reveal appearance against background" src="https://github.com/user-attachments/assets/9d9201ff-dfa0-4c9a-bd9d-b79cf51e461e" />

  - Seasons has a text to background contrast issue: 

    <img width="1000" alt="LC content in footer of site with Seasons theme. Text is grey with low contrast on dark greyish-blue background" src="https://github.com/user-attachments/assets/b76338d6-8408-49ba-b25d-75d94296ec7f" />

  - Lively is not displaying LC content in the footer at all.
- > Saving LC content as metadata (under Local Contexts tab) or as batch metadata edit, including selecting metadata field and saving as single & all languages respectively, and that it displays properly (i.e. as HTML with accompanying graphic) on both admin and public side
  - I am not seeing the accompanying graphics on either the admin or public side, just the HTML: 

    <img width="551" alt="Portion of admin dashboard. Project names listed above project descriptions in metadata" src="https://github.com/user-attachments/assets/351e4acb-96ca-46b1-9233-d7511a3965b8" />

    <img width="1213" alt="Portion of public page. Project names listed above project descriptions in metadata" src="https://github.com/user-attachments/assets/3a99fa08-1ae1-407a-ad9e-abf601e7e382" />

  - The Daily has a poorly aligned background color style behind project names (styled by `.element-text a`): 

    <img width="1239" alt="Detail on public page with The Daily theme. Bright yellow rectangles fill only a portion of the area behind project names" src="https://github.com/user-attachments/assets/3a79fdcc-c5d9-4b95-ae85-6b1a7f32f594" />

Other notes:
- I'm getting some container overflow on the assign page with longer project titles:

  <img width="567" alt="List of projects available on Local Contexts assign page. Longer project titles are extending past container, out of view" src="https://github.com/user-attachments/assets/6df5cd50-2eb1-440c-a97c-a0bf95940316" />

- Selecting content on the assign page is not exactly an accessible process. Via screen reader, it can be difficult to determine what items checkboxes are for since they come first in the sequence and do not provide context. Links are literally read out as links and do not identify their link text (i.e. a given project, perhaps this is due to the `aria-label` "expand" overriding these?). Toggles do not work via keyboard, although I know @kimisgold has been in the process of fixing this pattern across Classic.
  - The target size for checkboxes appears to be a bit too small (13x13). This should be at least 24x24. In addition to this failing [SC 2.5.8](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html), it is causing some overlap and accidental click with project links.

**Comment by matthewjmckinley** [comment]
Like the module, answers in order below:

-(fixed) All projects should be returning now--I implemented a pagination iterator in the API results.
- (open) Again, I'm going to create a sub-issue for theme display issues and ping Kim and Nelson.
- (open) I can't recreate this -- all of my LC content assigned as item metadata is showing the thumbnail as well. Could you let me know what exact project you are assigning, field you are assigning it to, and what the HTML looks like within the item edit screen after it gets assigned (screenshot and/or page source)?
- (kinda fixed) I fixed the overflow in the project title where it appears. However, this makes most of the div a link out to the project page, and only a narrow box to click the arrow to expand--not ideal. I'll add to the theming sub-issue.
- (open) I'll also add the `aria-label` and checkbox accessibility issues to the sub-issue.

**Comment by matthewjmckinley** [comment]
Oops, the Invalid Header error was also a bug and has been fixed!

**Comment by aviannamiller** [comment]
Thank you! Still having some issues with the following:

- > (fixed) All projects should be returning now--I implemented a pagination iterator in the API results.
    - Same issue as the module, I am seeing all projects from the Local Contexts Projects Board instead of just those attached to the API key
- > (open) I can't recreate this -- all of my LC content assigned as item metadata is showing the thumbnail as well. Could you let me know what exact project you are assigning, field you are assigning it to, and what the HTML looks like within the item edit screen after it gets assigned (screenshot and/or page source)?
    - Just tried to recreate using the following on [this item](https://dev.omeka.org/amiller/Classic/items/show/2044):
      - [Supporting Indigenous Relationships and Acknowledgements in Scientific Research with BC Labels](https://sandbox.localcontextshub.org/projects/41cceba1-f2d8-4890-85ec-8734168a7174/) is assigned to Date.
      - [plate with black-on-black feather design](https://sandbox.localcontextshub.org/projects/192fbafe-5a19-4159-9771-529719b7e9ce/) is assigned to Abstract.
    - When I assigned the former to the date, it did show the graphics this time. When I then assigned the latter to abstract, thumbnails disappeared from both except for two notices on the latter:
    
      <img width="256" alt="Edit HTML for Date metadata. All text, no graphics." src="https://github.com/user-attachments/assets/1e8c6e20-1523-4e3a-a6c9-42237cf6c226" />

      <img width="260" alt="Edit HTML for Abstract metadata. Mostly text, although two fields also include graphics." src="https://github.com/user-attachments/assets/8db1369e-3ee3-4aff-9d38-bf77cef17d6c" />

- > (kinda fixed) I fixed the overflow in the project title where it appears. However, this makes most of the div a link out to the project page, and only a narrow box to click the arrow to expand--not ideal. I'll add to the theming sub-issue.
    - I am not sure if this is a product of this change, but I now see that drawer toggle touch targets are a bit too small (20x20 px). They should be at least 24x24 px.

**Comment by matthewjmckinley** [comment]
Ah OK, I know what's happening with the images disappearing. For Classic, there's a security sanitization processes that runs when metadata is saved to make sure there's no nefarious HTML/scripts/files etc. getting saved to the database. The LC plugin kind of bypasses this process on the initial save (don't worry, I'm escaping HTML in the code itself), but when existing metadata values are 're-saved', i.e. when you add a metadata value, then click edit and add another metadata value, the sanitization process goes through and strips the images from the already existing metadata. This is why you are able to see the images saved to the metadata the first time but not any subsequent times.

To get around this, a user just needs to go into their Omeka Classic settings and add `img` to the Allowed HTML Elements list and `img.src` to Allowed HTML Attributes. I've just done this and your test site and things are saving correctly for me now, feel free to test yourself.

Thank you for the reminder, I'll be sure to include that bit for the LC Plugin Classic documentation issue.

As for the drawer toggle touch targets being small, I noted this as well and mentioned it in the display sub-issue for Kim/Nelson.

**Comment by aviannamiller** [comment]
Okay, great.

I just retested but am still getting a bit of weirdness with thumbnails not appearing on some notices as well as unloaded images on others. I am testing on [this item](https://dev.omeka.org/amiller/Classic/admin/items/show/id/2028) (and the [public item page](https://dev.omeka.org/amiller/Classic/items/show/2028)):

<img width="405" alt="Language metadata. Two entries have HTML with thumbnail graphics, while two others just have HTML" src="https://github.com/user-attachments/assets/2616429d-462a-4fa9-92e1-e4d7012cd5c3" />

<img width="405" alt="Type metadata. Two entries have HTML with thumbnail graphics, while two others have HTML accompanied by unloaded images" src="https://github.com/user-attachments/assets/889d240a-ed4f-4ec5-898a-b9c4c812e3c4" />

**Comment by matthewjmckinley** [comment]
That's an issue with the thumbnail URLs pulled from the LC sandbox/test server pointing to missing images or broken links. I noticed a few broken thumbnail links in my testing as well. I'm not sure why the TK Verified and CT Verificado thumbs under `Language` are simply missing in your screenshot--when I visit your site now they are appearing as `?` just like the other unloaded thumbs.

I'll note these broken links to the developer in my next email. Presumably the links will be better policed on the production server, but if it's still an issue after release, I can try to check the image URL before saving as metadata/displaying in an update.

**Comment by aviannamiller** [comment]
Also flagging the plugin for the issue of Project IDs being stored in the input box on the API Settings page, as discussed in https://github.com/omeka-s-modules/LocalContexts/issues/2#issuecomment-3064033012

**Comment by allanaaa** [comment]
I've just installed this plugin and have started to check out the work. 

I realize things can be confusing because we're using a sandbox API and not a real project that would make interpreting this workflow a little easier. I'll do my best with the docs to explain what happens on the LC website end. 

But I'm not clear on the way this is supposed to work in Omeka.

1) When I entered in the API key, I clicked away to look at the site footer setting. When I went back to the plugin entry in the sidebar, I was confronted with the same original blank form with two fields. Your setup right now is I have to click the "save" button on two blank fields in order to proceed to the next page, which is full of information from the API I entered earlier? That's really not intuitive. Can we combine these two screens into one? When you put in an API and it loads sucessfully, can the projects appear at the top of this page? And can the API you entered be saved and displayed in its field until you erase it? 
<img width="849" height="459" alt="Image" src="https://github.com/user-attachments/assets/93e43a05-b0d3-4d3f-9fa6-545de152160a" />

2) I notice that you can tag individual items as being part of a project but not collections? Can you add collections support? 

3) The site footer isn't appearing, for me, the way it appears in Omeka S - and the formatting is a big deal for understanding what's happening here. This needs more styling. 
<img width="1662" height="661" alt="Image" src="https://github.com/user-attachments/assets/36b39f28-7cdb-43e5-bb93-0a66f2b72fa6" />
<img width="1681" height="943" alt="Image" src="https://github.com/user-attachments/assets/86853bba-d569-4b2d-8e6c-f29460188e4b" />
<img width="1675" height="628" alt="Image" src="https://github.com/user-attachments/assets/5c65cbed-0a47-41ad-8e27-a6fce9319d1c" />

4) Can we have the ability to add explanatory text into the footer to help people contextualize what they are seeing? Just a project link and some notices doesn't appear to be enough. This is also loading ABOVE the footer text content, so even if I wanted to put explanatory text there, it wouldn't really help. 

5) Why is the API key "optional"? Can you do anything with this plugin if you leave that blank?

6) I would also move the plugin-config content over to the plugin sidebar entry. I don't know why the footer setting is separate. These are not plugin-specific config options. Maybe you could put that into the Appearance settings page instead, near the footer settings? If not, I would put them all on one page with the other options.

**Comment by allanaaa** [comment]
7. I am not sure about the way you are assigning LC notices/labels into metadata fields. Or, I'm not sure that makes the most sense. Maybe you can explain that approach to me. I would think the notices or labels would be most likely assigned to the "Rights" field, even though it's not quite that either. Maybe Provenance and a few others? But certainly not the entire list of available fields (Title, etc.). Alternatively, maybe LC can add a new element set and these labels can be appended like any other separate metadata schema?
8. Will there be redundancy? If the site has notices/labels in the footer, and the item view page also has notices/labels ... and the whole site is part of a project and each item is also part of the same project ... I feel like this will take up a lot of space on a page and be a bit repetitive. Particularly if we can't select specific labels for each item, rather than just showing all the notices/labels attached to a project every time. (Again, this may not be an issue with a real workflow, just with the sandbox content? I honestly am not sure.)
9. I think the way the content is appearing now could be improved so it's a little clearer by default. This is not the sort of plugin we want to toss off in an overly technical way. Maybe default text is more belaboured, like "This resource is part of the [Project] project of the Local Contexts Initiative. Click this link to learn more information on the Local Contexts website." And also some differentiation between what a label is and what a notice is, maybe different background colours or other design, and some helpful text there as well. "The appearance of a label indicates that this collection is from an Indigenous community."/"The appearance of a notice indicates that this collection may be of Indigenous interest." (We'll workshop this.) 
It's just too opaque, and we want to further this effort where we can, not normalize confusion about it.

**Comment by matthewjmckinley** [comment]
Before I start I will say a lot of these design/process decisions were decided with the LC folks, who were very particular about what their users want and how their content displays--there's a whole sensitive cultural context around this content that needs to be taken into account.
 
1. The process is the same as how the DSpace/Fedora/Data Repository connectors work--you enter credentials and specific project information, and get API results on the next page which you can then ingest/assign. If you leave the API key blank, it then only shows you the LC projects you've already pulled in to Omeka so you can edit/remove them, as the helper text states. LC folks wanted a 'bank' of LC projects to choose from, but not just pulling in all of a user's LC projects every time, because they may want to use only specific notices/labels for an Omeka site and didn't want to accidentally assign the wrong notice. I'm not having the API key persist because it's a password, and it's generally not good practice to store.
2. Collections support (or itemSet support in S) would add another layer of complication for setting and display. It's do-able but LC folks were happy with being able to assign at Site, individual item, batch item, and exhibit. Maybe for a future update if there's requests for it?
3. Yeah, that def needs some more formatting. Kim is on it here: https://github.com/omeka/plugin-LocalContexts/issues/3
4. I believe I initially had a title label above that, "Local Contexts Notices" or similar, and LC folks didn't want that, they preferred the notices/labels on their own. Presumably their users and those users' user base are aware of what the notices/labels mean, or they are including explanatory information somewhere else on the site.
5. As it says in the helper text, it's optional because a user may want to edit/remove LC content from the site, in which case they leave that field blank so it doesn't pull in new content and they can edit existing content.
6. Do you mean having the site assignment be in the plugin config page? I agree, it is tucked away and unintuitive, but there are Classic-specific technical reasons they are there. I wanted to put that in the Appearance settings but that's not configurable in the same way site settings are in S.
7. It's about giving the users flexibility in how they assign the LC content. I talked over cherry picking a few obvious fields like Rights, Provenance etc but the LC folks didn't want to limit what fields these could be assigned to.
8. Again, this is about flexibility. They wanted all those levels as options because people are using the notices/labels/Omeka in different ways. Presumably they wouldn't turn everything on all at once, but even if they did want to LC would prefer they have that option than limiting them. And having a whole projects notices/labels as an assign block is by design--I initially had it so users could assign individual labels, but LC folks insisted the whole project's content is a discrete unit that needs to stay together.
9. I don't disagree, but I don't think LC folks want context like that to be public facing, considering they didn't even want a title in the footer (see 4). There's a lot of contextual information we can link to from the documentation (https://localcontexts.org/about/), or maybe we could put a link to this with a short blurb on the initial API settings page. Would need to clear this with LC folks but I could do that during my final demo with them before going live.

**Comment by allanaaa** [comment]
1. I think we can still combine the project list and the first page into one, with the project list at the top once it's been pulled. Can you fill in the API field with asteriskes (asterixes? asterices?) instead of actually persisting anything? Just as a way to indicate in the UX? 
If I fill out the API field a second time, will it show projects from both, or will it erase the earlier and replace it with the new content?

**Comment by allanaaa** [comment]
4. Can we move the LC content below the footer text field anyways? Then people have the option to include some explanation there if desired. It should go: footer; LC content; copyright content.

**Comment by matthewjmckinley** [comment]
1. It would mean redesigning a fair bit of the module--having a form redirect to itself introduces complications and is not always best practice--and I guess I just don't see the issue. The other modules I mentioned above work in just this way and nobody seems confused by the process. And a 'fake' API key shown by pre-filled asterix seems like it might be more confusing from a UX perspective? It would trick users into thinking the field is populated when it's not. Plus there's a function associated with submitting an empty API field--removing existing LC content, if needed. Hence why it's optional.

As to your second question, it's not iterative--it only gives you projects associated with the API key you just put in, each time, like the other repository connectors/most of the module input forms.

4. That makes sense and feels like a good compromise, I'll see what I can do after finishing the accessibility changes I'm working on for Kim.

**Comment by allanaaa** [comment]
6. Yes, I think we could have all the plugin's settings on the same page, from the sidebar entry. I don't know that any of it qualifies as "plugin config". Having to go to the API screen and load content, then go back to the Plugins page and click the configuration button ... It's really awkward. 

What if: you enter in the API/projects, save the page, then a table loads with the intended projects - and there is a "Remove?" checkbox column and a "Footer?" checkbox column. (And the API and projects fields appear below the table.)

**Comment by allanaaa** [comment]
1. "I guess I just don't see the issue. The other modules I mentioned above work in just this way and nobody seems confused by the process."

Those modules offer a "Past imports" link in the sidebar that you can get to without saving a page of empty fields. 

And to be honest I think the OSII is the preferred workflow: it shows the existing connections on the home screen if you have any. Maybe this is an argument to get our S modules in line with each other and consistent too. If I had a vote I'd change the connectors to the OSII model. 

"a 'fake' API key shown by pre-filled asterix seems like it might be more confusing from a UX perspective? It would trick users into thinking the field is populated when it's not."

But it IS populated - or it HAS BEEN populated, that's where the existing connections come from. There is a problem with having a blank field indicate "An existing connection, which you can't see on this page, can be preserved if you leave this field blank and proceed to the next screen", definitely.

**Comment by matthewjmckinley** [comment]
I don't think users are going to be revisiting/re-entering this API key submission form nearly as often as other connectors. The LC notice/label content is static by design. Users pull in their preferred LC project/s with this form, then access them from an item, site, or exhibit context. Maybe they add more project/s later on, but it's not going to need regular updating like if we were actually pulling in full on metadata records.

A holistic reconfiguring of S modules and Classic plugins makes sense if it streamlines things for the user. But that's a larger project. I guess I'm just wondering if substantially redesigning the plugin and module at this stage is worth pushing back the release of something LC/Omeka users seem to want released, and which the LC team has already seen in action, understood and approved.

"But it IS populated - or it HAS BEEN populated, that's where the existing connections come from. There is a problem with having a blank field indicate "An existing connection, which you can't see on this page, can be preserved if you leave this field blank and proceed to the next screen", definitely."

But there's not really a 'persisting' connection here--you put the API key in, it pulls in and shows you the associated projects on the next screen, you decide which projects you want to 'use' for Omeka, click 'submit' and then those projects are available in other places (item/site/exhibit). After clicking submit, the plugin 'forgets' the API key, since it's a password and a security risk to store it in the database. When they revisit the form, it's starting fresh--the blank field indicates nothing other "If you want to pull in new LC project/s, enter your API key again. If you only want to see what you've already assigned, which is saved locally and doesn't require another LC API access, leave this blank".

**Comment by matthewjmckinley** [comment]
Footer fix is in with latest commit

**Comment by allanaaa** [comment]
Ah, sorry, I wasn't thinking the LC content would come after EVERYTHING - I was hoping it would come inside the footer, after the custom footer text as set in the Theme config, and before the copyright information, before the bottom nav if applicable, before the "Back to top" link if applicable, and certainly before the "Proudly powered by Omeka" line. 

What I'm seeing now is this:
<img width="1156" height="966" alt="Image" src="https://github.com/user-attachments/assets/ee59b1fa-d6a1-4a7c-baf8-fe7ef0e3342c" />

<img width="704" height="299" alt="Image" src="https://github.com/user-attachments/assets/476276d4-27bf-4074-a62d-0f0c9cfd6778" />

**Comment by matthewjmckinley** [comment]
It's not supposed to -- it's inserting between the footer text and copyright on mine, but your source code looks different than mine. I haven't seen `<div id="custom-footer-text">` before, mine is labeled `<div id="footer-text">`. Does it change between theme?

**Comment by allanaaa** [comment]
It might - you do have to enter in your text (and check the copyright box) in each theme settings page:

<img width="834" height="316" alt="Image" src="https://github.com/user-attachments/assets/17341d74-d507-4438-9b70-6873d26e6ab5" />

I made an issue about this in Thanks Roy yesterday, so probably related and needs to be tackled consistently across all our themes:
https://github.com/omeka/theme-thanksroy/issues/66

I've left my site on Foundation to fix those most glaring theme issues in #3 so that's hindered me in switching through themes. 

Just to confirm, I am on the master branch of Classic core (3.2) and all my themes are updated today. So if we want to release this plugin soon I could do a 3.1.2 install and get the stable theme versions instead of all these in-development versions. Would that help?

**Comment by matthewjmckinley** [comment]
That might help. Hard to say because it's a moving target with all the other theme work going on, but if we aim to release it soon getting everything working with the stable theme versions seems like the best approach.

I won't be able to get to it until next week, but I'll cycle through all the current stable themes and see if I can find a more consistent way to place the LC footer content.

**Comment by sharonmleon** [comment]
Just swinging in here to reinforce @matthewjmckinley's gut that redesigning Classic importers/plugins to mirror S's module user experience is way beyond what we're looking to do here. There are significant technical reasons why that's big job and not one that we're going to undertake at this point, including in the service of this one plugin. 

I want to call this feature complete and start adding issues for the next version, so we can get this out -- especially given all the consultation that the LC folks have given on how it should work. They'll be the ones training folks on the ground to use it.

**Comment by sharonmleon** [comment]
PS: Maybe helper text on the API key page can help with the confusion on the disappearing key credentials....

If you have input a key, you projects have been loaded. You only need to input a new key if you wish to connect to new projects.

Something better than that.

**Comment by aviannamiller** [comment]
For the plugin, providing the same note on potentially adding `autocomplete="off"` to API Key and Project ID fields, as described in https://github.com/omeka-s-modules/LocalContexts/issues/2#issuecomment-3094624631

**Comment by matthewjmckinley** [comment]
`autocomplete="off"` incorporated into input form with latest commit

**Comment by kimisgold** [comment]
The expand/collapse pattern for the admin side is in. It needs to be tested against `drawer-toggle-a11y-rebase` in the core.

**Comment by matthewjmckinley** [comment]
I'm on `drawer-toggle-a11y-rebase` with the latest plugin code and the toggles aren't working--it can't seem to find manageDrawers: 
`TypeError: Omeka.manageDrawers is not a function. (In 'Omeka.manageDrawers('#assign-drawer-list', '.local-contexts-multicheckbox-row')', 'Omeka.manageDrawers' is undefined)`

**Comment by aviannamiller** [comment]
> `autocomplete="off"` incorporated into input form with latest commit

Same as the module: looks good on Firefox and Safari, but still getting autocomplete on Chrome; that seems to be a browser-specific issue

**Comment by aviannamiller** [comment]
@kimisgold, @matthewjmckinley - a few issues with expand/collapse:

- `.drawer-toggle` icons are not all in alignment. For drawers with longer names, those toggles are slightly pushed forward inline:
  <img width="578" height="419" alt="Drawers with toggle icons highlighted. They are displaying at slightly different inline points in the drawers" src="https://github.com/user-attachments/assets/6e90bb62-5891-4540-9766-0411e6d32939" />
- Generally getting an "Expand, **expanded**, button" or "Expand, **collapsed**, button" announcement on the toggle. 
  - Toggles on the module are instead read out as "**Collapsed**, link, **expand**" or "**Expanded**, link, **collapse**"; this is definitely preferred. The `aria-label` (and `title`) are alternating appropriately there, whereas here they are not, so assumedly that's causing the difference.
- If there are less than three projects available in a list, they remain hidden under collapsible divs, unlike before (also unlike the module, which expands these out).



Unrelated to the above... some issues with labels:
- I just noticed an improperly assigned label within LC Exhibit Blocks:
  <img width="989" height="190" alt="Label highlighted on an exhibit block next to a dropdown selector. To the right, the HTML is open, revealing a duplicate assignment for the label" src="https://github.com/user-attachments/assets/9a682ccf-1268-4ffc-a987-04e8c420ae01" />
  The label for `blocks-0-options-lc-project-language` instead repeats the id for `blocks-0-options-lc-project-id`, so assistive tech is not picking up a proper label for its corresponding `select`.
- On the plugin config, the language `select` is also not picking up on what should be its corresponding label; I don't believe the label is assigned to it at all.
- Both metadata element and language `select` inputs are missing their label assignments in batch edit.

**Comment by kimisgold** [comment]
> If there are less than three projects available in a list, they remain hidden under collapsible divs, unlike before (also unlike the module, which expands these out).

My thinking is that the less than 3 logic is not immediately obvious to the user, making for an inconsistent experience. Even if there are few projects, their notice content can still be very verbose. My feeling is that if we're going to collapse them, collapse them all.

I've pushed fixes for the drawer toggle target sizing, as well as the various label issues. I'm still looking into what's going on with the Expand/Collapse label pattern.

**Comment by aviannamiller** [comment]
Thanks, labels are fixed, as are the toggles!

> My thinking is that the less than 3 logic is not immediately obvious to the user, making for an inconsistent experience. Even if there are few projects, their notice content can still be very verbose. My feeling is that if we're going to collapse them, collapse them all.

I definitely agree. In the module, checkboxes lose their accessible names when they fall out of the collapsible div pattern (see https://github.com/omeka-s-modules/LocalContexts/issues/2#issuecomment-3114428575); I'm sure the same would apply here, and that seems to overcomplicate ensuring accessible inputs, which the expand/collapse pattern is already dealing with here.

**Comment by kimisgold** [comment]
I've changed the drawer toggle labeling to say "Show details" and "Hide details". If that works, I think that addresses all the mentioned accessibility concerns.

**Comment by aviannamiller** [comment]
@kimisgold - I am now getting that reflexive label everywhere except for the plugin config; "Show details" is communicated whether the toggle has expanded or collapsed. This is true for VoiceOver, JAWS, and NVDA.

**Comment by aviannamiller** [comment]
Updates to the Local Contexts CSS for `.drawer-contents` are impacting other elements outside of the plugin that have this class.

I noticed this on the file uploads container on item edit pages, where `overflow: revert` is causing the following content overlap:

<img width="669" height="319" alt="Container for adding files. Content within the container is overflowing and overlapping with content in another container." src="https://github.com/user-attachments/assets/c3263d77-3936-4052-8dc8-570aff16599c" />

I'm unsure if this is negatively impacting any other elements that might have this class (for instance, VRA Core drawers have it but seem to be unaffected).

**Comment by aviannamiller** [comment]
Actually, this is also impacting fieldsets in VRA Core drawers:

<img width="369" height="544" alt="An open 'Display Attributes' drawer with a number of fieldsets. Fieldsets and labels are overflowing their container" src="https://github.com/user-attachments/assets/93f6f8cf-6f66-4a12-97f4-88d313fcb42a" />

Perhaps a distinct class is needed for LC to ensure other drawers across Classic haven't also adopted this overflow style?

**Comment by allanaaa** [comment]
Updating this morning, toggles are no longer working, and are appearing like this:

<img width="877" height="658" alt="Image" src="https://github.com/user-attachments/assets/4d15a25d-6d74-40d3-bd79-96ad0a3af981" />

**Comment by aviannamiller** [comment]
@allanaaa Are you on `drawer-toggle-a11y-rebase` on core? I'm not seeing this on my end.

**Comment by allanaaa** [comment]
Oh no, I'm sorry, I missed that part. 
Are we planning to release this plugin alongside a core release?

**Comment by kimisgold** [comment]
> Updates to the Local Contexts CSS for .drawer-contents are impacting other elements outside of the plugin that have this class.

Great catch. It looks like this must've been styles copied from the S module. I've removed them, so hopefully that'll fix the issues elsewhere in the admin.

> Oh no, I'm sorry, I missed that part. Are we planning to release this plugin alongside a core release?

Yes, that's the plan.

**Comment by aviannamiller** [comment]
> It looks like this must've been styles copied from the S module. I've removed them, so hopefully that'll fix the issues elsewhere in the admin.

Wonderful, that did it!

**Comment by matthewjmckinley** [comment]
@aviannamiller same here, is everything resolved and ready for release, pending documentation?

**Comment by aviannamiller** [comment]
All issues are resolved for me except for the following:

- > [@kimisgold](https://github.com/kimisgold) - I am now getting that reflexive label everywhere except for the plugin config; "Show details" is communicated whether the toggle has expanded or collapsed. This is true for VoiceOver, JAWS, and NVDA.
- Various theme-specific issues discussed in https://github.com/omeka/plugin-LocalContexts/issues/3
  - Some of these are more picky styling issues that should not in any way bar release, while others involve contrast issues which impede accessibility and should be prioritized. These involve Seasons, Santa Fe, and Thanks, Roy.

If you would like to move for release before a fix can be implemented, I can open a separate issue for the former.

**Comment by kimisgold** [comment]
Looks like I missed applying the label toggle on the config. That should be fixed now and is ready for a look.

**Comment by aviannamiller** [comment]
Thanks, that did it!

All of my observed issues are now resolved besides those that are theme-specific.

**Comment by allanaaa** [comment]
It appears I was wrong about what happens where all Projects have been removed from the site:

<img width="866" height="701" alt="Image" src="https://github.com/user-attachments/assets/afa0ef0b-3907-49a9-9c37-8c791e17102d" />

I removed all the projects in order to input a fresh API key. The error message is showing at the top of all tabs:

<img width="882" height="680" alt="Image" src="https://github.com/user-attachments/assets/e9078187-f007-4541-9125-6c8590490261" />

**Comment by allanaaa** [comment]
Small point but the "Assign labels & notices" screen can never display the full page title, no matter how wide your browser is:

<img width="1708" height="748" alt="Image" src="https://github.com/user-attachments/assets/4db538d1-db03-456e-8585-a1fb92daba09" />

"Assign Projects" or "Add Projects" might be better anyways.

**Comment by allanaaa** [comment]
Is there any more work planned to inject the site footer LC between the "footer text" field and the "copyright" field?

**Comment by kimisgold** [comment]
> Is there any more work planned to inject the site footer LC between the "footer text" field and the "copyright" field?

It's tricky figuring out a clean and consistent way to target that positioning, as it's dependent on whether there's footer text present or the copyright theme setting is checked. I would recommend outputting the LC content at the top or bottom of all footer content. If we need to fine tune the positioning, I would wait until after the first release and getting some user feedback on how footers are being laid out with this plugin.

**Comment by allanaaa** [comment]
Okay, I'll have to update a bit of the docs for that. Thanks. 

If we can eliminate that error message I just found when there are no projects, and change that one page title, I think we're good for a release.

**Comment by matthewjmckinley** [comment]
@allanaaa Assign page title has been updated.

I can't recreate the notices/warnings you're getting on the item edit page. However, I did make a change to more cleanly remove lc projects from the DB when they are deleted. Could you pull the latest code, add a new LC project and remove it (to trigger the new change and fully clear out the `lc_notices` option in the DB), and try again?

**Comment by allanaaa** [comment]
Okay, so now when there are no projects assigned the tab doesn't show at all in the item editing screen. Great. 

<img width="1116" height="599" alt="Image" src="https://github.com/user-attachments/assets/a8b4a4f7-3167-4d95-9cc6-0979a43ff1a1" />

**Comment by matthewjmckinley** [comment]
@allanaaa great! It looks like we are pretty much good to go on both S Module and Classic plugin, so I'll notify Ashley and we can plan for a release around the middle of next week?
